services:  
  db:  
    image: postgres:latest  
    restart: always  
    ports:  
      - 5432:5432
    environment:  
      POSTGRES_DB: training-platform-db  
      POSTGRES_USER: postgres  
      POSTGRES_PASSWORD: password  
    volumes:  
      - db:/var/lib/postgresql/data  
  flyway:  
    image: flyway/flyway  
    command: -url=jdbc:postgresql://db/training-platform-db -schemas=public -user=postgres  
      -password=password -connectRetries=5 migrate  
    volumes:  
      - ./db:/flyway/sql  
    depends_on:  
      - db  
  api:
    profiles: ["be"]
    build:
      context: ./server
      dockerfile: Dockerfile.local
    ports:
      - "3001:3001"
    volumes:
      - ./server:/app
    environment:
      DATABASE_URL: "postgres://postgres:password@db:5432/training-platform-db?schema=public"
volumes:  
  db: