FROM node:18-alpine

WORKDIR /app

# Install dependencies based on the preferred package manager
COPY package.json package-lock.json* ./
RUN  npm ci

COPY src ./src
COPY tailwind.config.ts .
COPY postcss.config.mjs .
COPY next.config.mjs .
COPY tsconfig.json .

# Environment variables must be present at build time
# https://github.com/vercel/next.js/discussions/14030
# ARG DATABASE_URL
# ENV DATABASE_URL=DATABASE_URL
# ARG NEXT_PUBLIC_DATABASE_URL
# ENV NEXT_PUBLIC_DATABASE_URL=NEXT_PUBLIC_DATABASE_URL

# Next.js collects completely anonymous telemetry data about general usage. Learn more here: https://nextjs.org/telemetry
# Uncomment the following line to disable telemetry at run time
# ENV NEXT_TELEMETRY_DISABLED 1

CMD npm run dev